# Generated by Django 5.1 on 2024-08-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_members_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleWebsite', models.CharField(max_length=200)),
                ('ArticleNumber', models.IntegerField()),
                ('ArticleName', models.CharField(max_length=200)),
            ],
        ),
    ]
