# Generated by Django 5.1 on 2024-08-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_articles_article_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
