# Generated by Django 5.1 on 2024-08-21 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_submissioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncount',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submissioncount',
            name='late_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submissioncount',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
