# Generated by Django 5.1 on 2024-08-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_submissioncount_deadline_submissioncount_late_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissioncount',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submissioncount',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissioncount',
            name='late_count',
            field=models.IntegerField(default=0),
        ),
    ]
