# Generated by Django 5.1 on 2024-09-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ArticleURL',
            field=models.URLField(default='https://google.com', max_length=500),
        ),
    ]
