# Generated by Django 5.1 on 2024-09-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_article_articleurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parents_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleURL',
            field=models.URLField(max_length=500),
        ),
    ]
