# Generated by Django 5.1 on 2024-09-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parents_email',
            new_name='parent_email',
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleURL',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
