# Generated by Django 5.1 on 2024-09-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_parents_email_user_parent_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parent_email',
            new_name='fathers_email',
        ),
        migrations.AddField(
            model_name='user',
            name='mothers_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
